@startuml
'https://plantuml.com/class-diagram

'Composition Relations (A has B)'
User *-- Project
Project *-- Task
Task *-- Reminder

'Dependency Relations (A use B)'
Task --> LocalDateTime
Reminder --> LocalDateTime

class Task {
- str name
- str description
- final int id
- LocalDateTime dueDateTime
- int priority
- boolean completed
- List<Reminder> reminders
}

class Project {
- str name
- final int id
- Map tasks
- boolean archived
}

class User{
- str name
- final str username
- final str password
- Map projects
}

class Reminder{
- str name
- str description
- LocalDateTime remindDateTime
}


@enduml